C++/Lapindromes.cpp

Added Lapindrome Code

---

K_Foldable_String.cpp

added K foldable String Code

---

D_Knapsack_1.cpp

Added Knapsack Code

---

C++/B_Sort_the_Array.cpp

Added sort Array Code

---

CONTRIBUTORS.md
Calculator.cpp

Hi! I made added a Calculator made in C++ and updated Contributors.md
Please add the hacktoberfest labels to this pr.
Thanks.

Added Calculator in C++

---

Fibonacci_DP
Subset Sum

This code will use DP to solve the Fibonacci Problem

Fibonacci_DP

---

C++/FibonacciSequence.cpp
CONTRIBUTORS.md

Updated CONTRIBUTED.md and added C++ Program for printing first n terms of Fibonacci Sequence MODULO 1e9+7

Added C++ Program for printing Fibonacci Sequence

---

C++/quick_sort.cpp

a simple c++ algorithm for sorting arrays using quick sort

create quick sort

---

C++/LargeNumFactorial.cpp

Please add Hacktober fest Accepted label

Created LargeNumFactorial.cpp

---

PHP/LeapYear.php

To check whether a year is a leap year

check leap year

---

C++/floyd_warshall.cpp

@aman1210  please review it and let me know if any changes are required.

Floyd_Warshall Algorithm added

---

Java/BSTreeAlgo.java

Add Binary-Search-Tree Algorithm

---

C++/hello_world.cpp
CONTRIBUTORS.md

Added hello world program in cpp

Jigar shah

---

.vscode/settings.json
Hacktob3r/index.html
Hacktob3r/index.js
Hacktob3r/styles.css

A quick website with a JavaScript background color changer enjoy :).

Hacktober Fest 2021 color change website

---

C/factorial

I added Factorial Program in C

Added Factorial Program in C

---

C++/insertion sort.cpp

Code for insertion sort in C++

Create insertion sort.cpp

---

C++/shell sort.cpp

Create shell sort.cpp

---

Java/OrderedArray.java

This program can be used to sort elements in an array in ascending order

OrderedArray.java

---

Python/Rock paper scissors.ipynb

If you’re unfamiliar, rock paper scissors is a hand game for two or more players. Participants say “rock, paper, scissors” and then simultaneously form their hands into the shape of a rock (a fist), a piece of paper (palm facing downward), or a pair of scissors (two fingers extended). The rules are straightforward:
- Rock smashes scissors.
- Paper covers rock.
- Scissors cut paper.

Rock paper scissors

---

C++/returngift.cpp

Return Gift(a prime no problem)

Return Gift(a prime no problem)

---

C++/heap sort.cpp
C++/merge sort.cpp

Code for Heap Sort and Merge Sort in C++

Create heap sort.cpp

---

C/MergeSort.c

Created program for Merge Sort in C

 MergeSort.c

---

CONTRIBUTORS.md

Added a new flutter project BMI calculator.

New Flutter Project BMI-Calculator

---

CONTRIBUTORS.md
Leetcode/Longest Common Prefix.cpp

[Y] - Added myself to CONTRIBUTORS.md file
[Y] - Added solution to LeetCode problem number 14

added myself

---

.idea/.gitignore
.idea/Hacktoberfest2021.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
Java/InsertionSort.java

Create Insertion Sort Data Structure using Java

Create Insertion Sort in java
